source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'jwt'
gem 'bcrypt'
gem 'openssl'
gem 'json'
gem 'rack'
gem 'rack-cors'
gem 'puma'
gem 'rake'

group :test do
  gem 'rspec'
  gem 'rack-test'
  gem 'simplecov'
end

group :development do
  gem 'pry'
  gem 'rubocop'
end