source 'https://rubygems.org'

ruby '3.2.0'

# Rails framework
gem 'rails', '~> 7.1.0'

# Database
gem 'sqlite3', '~> 1.6'

# Web server
gem 'puma', '~> 6.0'

# JSON API
gem 'jbuilder'

# Authentication & JWT
gem 'jwt', '~> 2.7'
gem 'bcrypt', '~> 3.1'

# Cryptography
gem 'openssl', '~> 3.1'
gem 'rbnacl', '~> 7.1'  # For additional crypto operations

# Password hashing
gem 'argon2', '~> 2.1'

# Caching
gem 'redis', '~> 5.0'
gem 'connection_pool', '~> 2.4'

# Logging
gem 'lograge', '~> 0.13'

# CORS
gem 'rack-cors', '~> 2.0'

group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'rspec-rails', '~> 6.0'
  gem 'factory_bot_rails', '~> 6.2'
  gem 'faker', '~> 3.2'
end

group :development do
  gem 'web-console'
  gem 'rack-mini-profiler'
  gem 'listen', '~> 3.8'
  gem 'spring'
end

group :test do
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'webdrivers'
  gem 'shoulda-matchers', '~> 5.3'
  gem 'database_cleaner-active_record', '~> 2.1'
end